### ISSUE TITLE
How to resize and crop at different size?

### ISSUE THREAD

**Issue by myyellowshoe** [JrSchild/jr-crop#30]
I know technically jrcrop is setup to handle profile size images, around 200 to 300 in HxW.
Though in my case I'd like to use it as a way for people to resize and crop images with a larger end size, say around 640x640.

How might I manipulate the canvas size / ratios to get end result size to be larger?

Ultimately the size I'm going for is something close to instagram size with the result.

Thanks for any thoughts!
Justin

**Comment by JrSchild** [comment]
I got you covered, jr-crop returns the maximum possible resolution for the passed dimensions. So if you set the crop area (width/height options) to 200x200, the resulting picture will always be square but have likely a much higher resolution depending on the passed image.

If you like the crop-area to be larger than your target devices you can use the screenWidth to increase it accordingly:

```
var width = window.innerWidth * 0.9; // Add a small margin.

options.width = width;
options.height = width;
```

In a future release I want to build this in by default.

**Comment by myyellowshoe** [comment]
Ahhh gotcha. Great to know. That would be helpful to have in by default.

I know you don't handle resizing in the plugin right now, though In my case i'm not worried about the absolute highest quality photo, also I've found some downsampling techniques online that might help reduce the effect on quality (http://stackoverflow.com/questions/18922880/html5-canvas-resize-downscale-image-high-quality)
That said, I'm working on including image resizing into the mix, any thoughts, opinions on how I might best go about this adding resizing into this?

Thanks again

**Comment by JrSchild** [comment]
Resizing on the client with proper quality causes headaches, fine tuning, comparing images, benchmarking, reading, etc... If you're fine with what client side algorithms produce and the quality of their output, go for it.

My recommendation would be to resize it on the server with proper native tools like ImageMagick or [Sharp](https://github.com/lovell/sharp). The latter even supports streaming, so you might even pipe the incoming data on the server straight through sharp.

**Comment by myyellowshoe** [comment]
Ideally it would be great if it was completely mobile, but the more I dive into this I'm realizing its probably not worth it. Was thinking it would be faster to do it locally with resizing and such, but just seeing all the potential memory issues (even on native ios/android) is making me leary about moving that way.

Sharp looks pretty interesting, i've got an nodejs back end anyways to this app, so might as well just go for it and do the resizing and such on the server.

Appreciate your thoughts.

**Comment by JrSchild** [comment]
As an experiment it would be cool to try to implement the [hermite-resize](https://github.com/viliusle/Hermite-resize) algorithm in webgl with vertex-shaders. It's non blocking. I looked a bit into it and seems like the GPU might be able to effectively execute it in parallel. If it would actually be good for this library is obviously another question, but it would be cool to see if it provides a significant performance improvement and good output quality.

**Comment by myyellowshoe** [comment]
Interesting.  Wondering how it will hold up on mobile, but what the hey worth the shot. i'll let you know what happens.

**Comment by JrSchild** [comment]
I also started experimenting with this. A couple of things to note so far:

Sending raw channel data is too big for the GPU so the source image needs to be passed as texture. A texture has to be square and has the dimensions of powers by 2. So 1x1, 2x2, 256x256, etc... Luckily webgl can take care of placing the image in a square texture for us. A 400x600 image will be placed in a 1024x1024 texture. However the maximum size is dependent on the GPU of the device as defined in `webgl.getParameter(webgl.MAX_TEXTURE_SIZE)`. This is usually somewhere around 4096x4096, it's unlikely the source image will exceed this, but if so it will require multiple textures resulting in complex GLSL code.

Pixel data is read from textures with coordinates ranging from (-1.0, -1.0) to (1.0, 1.0). These need to be re-calculated to the texture src-image's coordinates. I presume 64 bit floating point values are precise enough to get the exact 4-channel values, otherwise it will do its own interpolation and the algorithm won't be as precise anymore.

The hermite algorithm is very well to run in a fragment shader. These shaders are run for each target pixel on the canvas. The algorithm also runs for each target pixel and can be optimized with extremely high parallel computations and vector operators making it even faster. The only thing that might make it slower is kernel-initialization/compilation, passing parameters and/or creating the texture.

**Comment by JrSchild** [comment]
Pretty cool. I got a proof of concept working. It's super fast but still produces slightly different results and alpha channels aren't working properly yet.

https://github.com/JrSchild/hermite-resize-webgl
